import type { Metadata } from "next";
import "./globals.css";
import { Box, ChakraProvider } from "@chakra-ui/react";
import { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import theme from "@/config/theme";
export const metadata: Metadata = {
  title: "Recipe Hub",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" type="image/x-icon" />
      </head>
      <body>
        <ChakraProvider>
          <Box>
            <Navbar />
            <Box as="main">
              {children}
            </Box>
          </Box>
        </ChakraProvider>
      </body>
    </html>
  );
}
